FROM python:3.12-slim

# Set working directory
WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        wget \
        perl \
        build-essential \
        fontconfig \
        latexmk \
        texlive-full && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
