name: CI and Docker Publish

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install DejaVu and Ghostscript (Ubuntu)
        run: sudo apt-get update -y && sudo apt-get install fonts-dejavu ghostscript -y

      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Install dependencies with UV
        run: uv sync --locked --all-groups

      - name: Run Pyright type check
        run: uv run pyright

      - name: Run Ruff linter
        run: uv run ruff check .

      - name: Run Pytest
        run: uv run pytest

  docker:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tag
        id: vars
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "IMAGE_TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Set lowercase repository owner
        run: |
          echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/cv-tuner:${{ env.IMAGE_TAG }}
